"""specmap hook — manage git hooks for specmap."""

from __future__ import annotations

import os
import stat
from pathlib import Path

import typer

from specmap.cli import app
from specmap.cli.output import get_console

hook_app = typer.Typer(name="hook", help="Manage git hooks for specmap.")
app.add_typer(hook_app)

_HOOK_MARKER = "# specmap-managed-hook"
_HOOK_CONTENT = f"""\
#!/bin/sh
{_HOOK_MARKER}
# Auto-generated by specmap. Run 'specmap hook uninstall' to remove.
specmap annotate --json >/dev/null 2>&1 &
"""


@hook_app.command()
def install(ctx: typer.Context):
    """Install a post-commit hook that runs specmap annotate."""
    repo_root = ctx.obj["repo_root"]
    no_color: bool = ctx.obj["no_color"]
    console = get_console(no_color)

    if not repo_root:
        typer.echo("Error: must be run inside a git repository", err=True)
        raise typer.Exit(code=1)

    hook_path = Path(repo_root) / ".git" / "hooks" / "post-commit"

    if hook_path.exists():
        existing = hook_path.read_text(encoding="utf-8")
        if _HOOK_MARKER in existing:
            console.print("specmap post-commit hook is already installed.")
            return
        # Non-specmap hook exists — don't clobber it
        console.print(
            "A post-commit hook already exists and was not created by specmap.\n"
            "To add specmap, append the following to .git/hooks/post-commit:\n",
            style="yellow",
        )
        console.print("  specmap annotate --json >/dev/null 2>&1 &\n")
        raise typer.Exit(code=1)

    # Create hooks directory if needed
    hook_path.parent.mkdir(parents=True, exist_ok=True)

    hook_path.write_text(_HOOK_CONTENT, encoding="utf-8")
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC)

    console.print("Installed specmap post-commit hook.", style="green")


@hook_app.command()
def uninstall(ctx: typer.Context):
    """Remove the specmap post-commit hook."""
    repo_root = ctx.obj["repo_root"]
    no_color: bool = ctx.obj["no_color"]
    console = get_console(no_color)

    if not repo_root:
        typer.echo("Error: must be run inside a git repository", err=True)
        raise typer.Exit(code=1)

    hook_path = Path(repo_root) / ".git" / "hooks" / "post-commit"

    if not hook_path.exists():
        console.print("No post-commit hook found.")
        return

    content = hook_path.read_text(encoding="utf-8")
    if _HOOK_MARKER not in content:
        console.print("Post-commit hook was not created by specmap. Nothing to remove.")
        return

    # Remove specmap lines from the hook
    lines = content.splitlines(keepends=True)
    filtered = []
    skip_block = False
    for line in lines:
        if _HOOK_MARKER in line:
            skip_block = True
            continue
        if skip_block:
            # Skip comment and command lines following the marker
            stripped = line.strip()
            if stripped.startswith("#") or stripped.startswith("specmap ") or stripped == "":
                continue
            skip_block = False
        filtered.append(line)

    remaining = "".join(filtered).strip()
    if not remaining or remaining == "#!/bin/sh":
        # Only specmap content — delete the file
        hook_path.unlink()
        console.print("Removed specmap post-commit hook.", style="green")
    else:
        # Other content remains — write it back
        hook_path.write_text("".join(filtered), encoding="utf-8")
        console.print("Removed specmap section from post-commit hook.", style="green")


@hook_app.command(name="status")
def hook_status(ctx: typer.Context):
    """Check if the specmap post-commit hook is installed."""
    repo_root = ctx.obj["repo_root"]
    no_color: bool = ctx.obj["no_color"]
    console = get_console(no_color)

    if not repo_root:
        typer.echo("Error: must be run inside a git repository", err=True)
        raise typer.Exit(code=1)

    hook_path = Path(repo_root) / ".git" / "hooks" / "post-commit"

    if hook_path.exists():
        content = hook_path.read_text(encoding="utf-8")
        if _HOOK_MARKER in content:
            is_executable = os.access(hook_path, os.X_OK)
            if is_executable:
                console.print("specmap post-commit hook: installed", style="green")
            else:
                console.print(
                    "specmap post-commit hook: installed (not executable!)",
                    style="yellow",
                )
            return

    console.print("specmap post-commit hook: not installed")
