"""Read/write .specmap/{branch}.json tracking files."""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from specmap.state.models import CodeReviewFile, SpecmapFile, WalkthroughFile


def _ensure_gitignore(specmap_dir: Path) -> None:
    """Create .specmap/.gitignore if it doesn't already exist."""
    gitignore = specmap_dir / ".gitignore"
    if gitignore.exists():
        return
    gitignore.write_text("# Auto-generated by specmap\n*.db\n", encoding="utf-8")


class SpecmapFileManager:
    """Manages .specmap/{branch}.json files."""

    def __init__(self, repo_root: str):
        self.repo_root = Path(repo_root)

    def get_branch(self) -> str:
        """Get the current git branch name."""
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                cwd=str(self.repo_root),
                capture_output=True,
                text=True,
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except FileNotFoundError:
            pass
        return "unknown"

    def get_base_branch(self, configured: str | None = None) -> str:
        """Detect the base branch (default: main, fallback: master).

        If *configured* is set, verify it exists as a git ref and return it.
        Falls back to auto-detect if the configured ref doesn't exist.
        """
        if configured:
            try:
                result = subprocess.run(
                    ["git", "rev-parse", "--verify", configured],
                    cwd=str(self.repo_root),
                    capture_output=True,
                    text=True,
                )
                if result.returncode == 0:
                    return configured
            except FileNotFoundError:
                pass
            print(
                f"[specmap] Warning: configured base_branch '{configured}' "
                f"not found as a git ref, falling back to auto-detect",
                file=sys.stderr,
            )

        for candidate in ("main", "master"):
            try:
                result = subprocess.run(
                    ["git", "rev-parse", "--verify", candidate],
                    cwd=str(self.repo_root),
                    capture_output=True,
                    text=True,
                )
                if result.returncode == 0:
                    return candidate
            except FileNotFoundError:
                break
        return "main"

    def _sanitize_branch(self, branch: str) -> str:
        """Convert branch name to safe filename: replace / with --, reject traversal."""
        sanitized = branch.replace("/", "--")
        # Reject path traversal sequences and null bytes
        if ".." in sanitized or "\x00" in sanitized:
            raise ValueError(f"Invalid branch name: {branch!r}")
        return sanitized

    def _specmap_dir(self) -> Path:
        """Get the .specmap/ directory path."""
        return self.repo_root / ".specmap"

    def _file_path(self, branch: str) -> Path:
        """Get the path for a branch's tracking file."""
        return self._specmap_dir() / f"{self._sanitize_branch(branch)}.json"

    def ensure_dir(self) -> None:
        """Create .specmap/ directory if needed."""
        d = self._specmap_dir()
        d.mkdir(parents=True, exist_ok=True)
        _ensure_gitignore(d)

    def load(self, branch: str | None = None) -> SpecmapFile:
        """Load from .specmap/{branch}.json. Returns empty SpecmapFile if not found."""
        if branch is None:
            branch = self.get_branch()

        path = self._file_path(branch)
        if not path.exists():
            return SpecmapFile(
                branch=branch,
                base_branch=self.get_base_branch(),
            )

        try:
            with open(path) as f:
                data = json.load(f)
            return SpecmapFile.model_validate(data)
        except (json.JSONDecodeError, OSError, ValueError) as e:
            print(f"[specmap] Warning: failed to load {path}: {e}", file=sys.stderr)
            return SpecmapFile(
                branch=branch,
                base_branch=self.get_base_branch(),
            )

    def save(self, data: SpecmapFile) -> Path:
        """Write to .specmap/{branch}.json with pretty JSON."""
        self.ensure_dir()
        data.updated_at = datetime.now(timezone.utc)

        path = self._file_path(data.branch)
        json_str = data.model_dump_json(indent=2)
        path.write_text(json_str, encoding="utf-8")
        return path

    def _walkthrough_path(self, branch: str, familiarity: int, depth: str) -> Path:
        """Get the path for a branch's walkthrough file."""
        sanitized = self._sanitize_branch(branch)
        return self._specmap_dir() / f"{sanitized}.walkthrough.f{familiarity}.{depth}.json"

    def load_walkthrough(self, branch: str, familiarity: int, depth: str) -> WalkthroughFile | None:
        """Load .specmap/{branch}.walkthrough.f{familiarity}.{depth}.json. Returns None if not found."""
        path = self._walkthrough_path(branch, familiarity, depth)
        if not path.exists():
            return None
        try:
            with open(path) as f:
                data = json.load(f)
            return WalkthroughFile.model_validate(data)
        except (json.JSONDecodeError, OSError, ValueError) as e:
            print(f"[specmap] Warning: failed to load {path}: {e}", file=sys.stderr)
            return None

    def save_walkthrough(self, data: WalkthroughFile) -> Path:
        """Write to .specmap/{branch}.walkthrough.json with pretty JSON."""
        self.ensure_dir()
        data.updated_at = datetime.now(timezone.utc)

        path = self._walkthrough_path(data.branch, data.familiarity, data.depth)
        json_str = data.model_dump_json(indent=2)
        path.write_text(json_str, encoding="utf-8")
        return path

    def _code_review_path(self, branch: str) -> Path:
        """Get the path for a branch's code review file."""
        sanitized = self._sanitize_branch(branch)
        return self._specmap_dir() / f"{sanitized}.code-review.json"

    def load_code_review(self, branch: str) -> CodeReviewFile | None:
        """Load .specmap/{branch}.code-review.json. Returns None if not found."""
        path = self._code_review_path(branch)
        if not path.exists():
            return None
        try:
            with open(path) as f:
                data = json.load(f)
            return CodeReviewFile.model_validate(data)
        except (json.JSONDecodeError, OSError, ValueError) as e:
            print(f"[specmap] Warning: failed to load {path}: {e}", file=sys.stderr)
            return None

    def save_code_review(self, data: CodeReviewFile) -> Path:
        """Write to .specmap/{branch}.code-review.json with pretty JSON."""
        self.ensure_dir()
        data.updated_at = datetime.now(timezone.utc)

        path = self._code_review_path(data.branch)
        json_str = data.model_dump_json(indent=2)
        path.write_text(json_str, encoding="utf-8")
        return path

    def delete_files(self, branch: str) -> None:
        """Delete annotation and all walkthrough variant files for a branch."""
        self._file_path(branch).unlink(missing_ok=True)
        sanitized = self._sanitize_branch(branch)
        for pat in (
            f"{sanitized}.walkthrough.f*.*.json",
            f"{sanitized}.walkthrough.json",
            f"{sanitized}.code-review.json",
        ):
            for path in self._specmap_dir().glob(pat):
                try:
                    path.unlink(missing_ok=True)
                except OSError:
                    pass
